import test from 'node:test';
import assert from 'node:assert/strict';
import {captureView,applyView,changedSources,createRefreshCoordinator} from '../plugins/gamecaden/panels/night/panel-refresh.mjs';
import {domainTree,focusSourceData,chapterText} from '../plugins/gamecaden/panels/night/domain-reader.mjs';
import {relationViewIdentity} from '../plugins/gamecaden/panels/night/relations.mjs';

const version=(digest='a',rows=[['spec/a.md','1']])=>({complete:true,digest,source_revisions:rows.map(([path,revision])=>({ref:{path},revision}))});
const setup=()=>{
  let bound={id:'A',binding:'root-a'},next=version(),blocked=false;
  const calls=[],statuses=[];
  const coordinator=createRefreshCoordinator({context:()=>bound,readVersions:async saved=>{calls.push(['versions',saved.id]);return next;},loadChanges:async(saved,change)=>{calls.push(['load',saved.id,change]);return next;},blocked:()=>blocked,status:kind=>statuses.push(kind)});
  coordinator.prime(bound,next);
  return {coordinator,calls,statuses,setVersion:value=>next=value,setBlocked:value=>blocked=value,setContext:value=>bound=value};
};
test('unchanged foreground checks do not load or rebuild project data',async()=>{const x=setup();assert.equal((await x.coordinator.check()).kind,'unchanged');assert.deepEqual(x.calls,[['versions','A']]);});
test('modified source yields paths while additions/deletions preserve membership changes',()=>{assert.deepEqual(changedSources(version(),version('b',[['spec/a.md','2'],['spec/new.md','1']])),{paths:['spec/a.md','spec/new.md'],membershipChanged:true});assert.deepEqual(changedSources(version(),version('b',[])),{paths:['spec/a.md'],membershipChanged:true});});
test('active editing defers refresh, then applies the change without accepting a premature baseline',async()=>{const x=setup();x.setVersion(version('b'));x.setBlocked(true);assert.equal((await x.coordinator.check()).kind,'deferred');assert.equal(x.coordinator.baseline({id:'A',binding:'root-a'}).digest,'a');assert.equal(x.calls.filter(call=>call[0]==='load').length,0);x.setBlocked(false);assert.equal((await x.coordinator.check()).kind,'updated');assert.equal(x.coordinator.pending(),false);});
test('incomplete or failed source checks never become an unchanged/latest result',async()=>{const x=setup();x.setVersion({complete:false,digest:null,diagnostics:[{code:'revision_conflict'}]});assert.equal((await x.coordinator.check()).kind,'incomplete');assert.equal(x.coordinator.baseline({id:'A',binding:'root-a'}).digest,'a');assert.equal(x.calls.filter(call=>call[0]==='load').length,0);});
test('successful write invalidates even an unchanged source digest and preserves affected identity',async()=>{const x=setup();x.coordinator.invalidate({id:'A',binding:'root-a'},'record:asset');await x.coordinator.check();assert.deepEqual(x.calls.find(call=>call[0]==='load')[2].keys,['record:asset']);});
test('coalesced checks share the request and ignore a different binding response',async()=>{let finish;let bound={id:'A',binding:'one'};let loads=0;const x=createRefreshCoordinator({context:()=>bound,readVersions:()=>new Promise(resolve=>finish=resolve),loadChanges:async()=>{loads++;return version();},blocked:()=>false});const a=x.check(),b=x.check();bound={id:'A',binding:'two'};finish(version());assert.equal((await a).kind,'superseded');assert.equal((await b).kind,'superseded');assert.equal(loads,0);});
test('a second write during refresh remains pending rather than being lost',async()=>{let finish;const bound={id:'A',binding:'one'};const x=createRefreshCoordinator({context:()=>bound,readVersions:async()=>version('b'),loadChanges:()=>new Promise(resolve=>finish=resolve),blocked:()=>false});x.prime(bound,version('a'));x.invalidate(bound,'first');const work=x.check();await new Promise(resolve=>setImmediate(resolve));x.invalidate(bound,'second');finish(version('b'));await work;assert.equal(x.pending(),true);});
test('reading restoration clones sets/maps and never replaces drafts or frozen requests',()=>{const original={page:'documents',selectedKey:'doc',documentFragment:'原约束条目',selectedCandidateId:'C-2',mediaIndex:2,relationExpanded:new Set(['parent']),relationMemory:new Map([['key',{top:44}]]),relationReader:{nodeKey:'doc',fragment:'原约束条目',record:{body:'old'}},drafts:{task:{body:'local'}},pending:[{payload:{ticket:'frozen',body:'old'}}]};const saved=captureView(original);const next={drafts:original.drafts,pending:original.pending};applyView(next,saved);assert.equal(next.documentFragment,'原约束条目');assert.equal(next.selectedCandidateId,'C-2');assert.equal(next.mediaIndex,2);next.relationExpanded.add('other');assert.equal(original.relationExpanded.size,1);assert.equal(next.relationReader.record,null);assert.equal(next.drafts,original.drafts);assert.equal(next.pending,original.pending);});
const data={nodes:[{key:'a',record_key:'a',title:'总规范',group:'art',navigation_domain:'art'},{key:'b',record_key:'b',title:'子规范',group:'art',navigation_domain:'art',navigation_parent_key:'a'},{key:'orphan',record_key:'orphan',title:'独立参考',group:'art',navigation_domain:'art'},{key:'external',record_key:'external',title:'外部政策',group:'verify',navigation_domain:'verify',external:true}],edges:[{id:'edge',from:'external',to:'b',relation:'provides_policy'}],groups:['art','verify']};
test('document tree retains declared children, unconnected records and outside endpoints',()=>{const before=JSON.stringify(data),tree=domainTree(data);assert.deepEqual(tree.inside.map(node=>node.key),['a','orphan']);assert.deepEqual(tree.children.get('a').map(node=>node.key),['b']);assert.equal(tree.outside[0].key,'external');assert.equal(JSON.stringify(data),before);});
test('focus graph only selects existing original edges and keeps reading parent context',()=>{const selected=focusSourceData(data,'b');assert.deepEqual(selected.nodes.map(node=>node.key),['a','b','external']);assert.equal(selected.edges[0],data.edges[0]);assert.equal(focusSourceData(data,'b',false),data);});
test('chapter boundaries ignore fenced headings and stop at the next real peer or governance block',()=>{const body='## A\ntext\n```md\n## example\n```\n### nested\nmore\n## B\nnext';assert(!chapterText(body,'A').text.includes('next'));assert(chapterText(body,'A').text.includes('## example'));assert(!chapterText('## A\ntext\n<!-- workflow:governance -->\n{}','A').text.includes('{}'));assert.equal(chapterText(body,'missing').located,false);});
test('reader and selected-node focus diagrams have distinct viewport identities',()=>{const g={nodes:data.nodes,edges:data.edges};const common={mode:'sources',lens:'impact',scope:'all',domainFocus:'art',direction:'DOWN',focusOnly:true};assert.notEqual(relationViewIdentity(g,null,{...common,domainView:'tree'}),relationViewIdentity(g,null,{...common,domainView:'graph'}));assert.notEqual(relationViewIdentity(g,null,{...common,domainView:'graph',selectionKey:'a'}),relationViewIdentity(g,null,{...common,domainView:'graph',selectionKey:'b'}));});
test('document reader memory is independent of graph direction, lens and selection',()=>{const g={nodes:data.nodes,edges:data.edges},ui={mode:'sources',domainFocus:'art',scope:'all',domainView:'tree',direction:'DOWN',lens:'domains',selectionKey:'a'};assert.equal(relationViewIdentity(g,null,ui),relationViewIdentity(g,null,{...ui,direction:'RIGHT',lens:'impact',selectionKey:'b',focusOnly:false}));});
